config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'logout', to: 'web/users/sessions#destroy'
  get 'sign_in', to: 'web/users/sessions#new'
  post 'sign_in', to: 'web/users/sessions#create'
  get 'sign_up', to: 'web/users/users#new'
  post 'sign_up', to: 'web/users/users#create'
  
  scope module: 'web' do
    scope module: 'admin' do
      resources :users, only: [:index]
      resources :tasks
    end

    scope module: 'users' do
      resources 'users', only: [:show, :edit, :update] do
        resources :tasks
      end
    end
  end  

  root 'web/admin/tasks#index'
end

app/views/shared/_admin_fields.html.slim
= f.input :user_id, collection: User.where(role: 'user'), label_method: :email, value_method: :id, include_blank: false, input_html: {class: 'selectpicker'}

app/views/shared/_buttons.html.slim
= f.button :submit, 'Save', class: 'btn btn-primary'
- if (action_name != 'new') && (@task.current_state.events != {})
  .well
    - @task.current_state.events.keys.each do |transition|
      = f.button :submit, transition.to_s.camelize + ' task', name: "event[#{transition.to_s}!]", class: 'btn btn-success'

app/views/shared/_form.html.slim
.form-task
  - if current_user.role == 'admin'
    = simple_form_for @task, html: {multipart: true} do |f|
      = render 'shared/form_fields', f: f
      = render 'shared/admin_fields', f: f
      = render 'shared/buttons', f: f
  - else
    = simple_form_for [:user, @task], html: {multipart: true} do |f|
      = render 'shared/form_fields', f: f
      = render 'shared/buttons', f: f

app/views/shared/_form_fields.html.slim
.form-group
  = f.input :name, input_html: {class: 'form-control'}
  = f.input :description, as: :text, input_html: {class: 'form-control', rows: '5'}
  - if @task.document.content_type
    - if @task.image_attached?
      = image_tag @task.document.url, class: 'image-size'
    - else
      = link_to @task.document.file.filename, @task.document.url
  = f.input :document, as: :file

app/views/shared/_task.html.slim
tr
  td.col-md-1 = task.id
  - if current_user
    - if current_user.role == 'admin'
      td.col-md-3 = link_to task.name, task_path(id: task.id)
    - else
      td.col-md-3 = link_to task.name, user_task_path(user_id: current_user.id, id: task.id)
  - else
    td.col-md-3 = task.name

  td.col-md-4 = task.description
  td.col-md-1 = task.current_state

  - if current_user 
    - if current_user.role == 'admin'
      td = task.user.email
      td.col-md-3
        .btn-group
          = button_to 'Edit task', edit_task_path(task.id), class: 'btn-xs btn-primary', method: :get
          = button_to 'Delete task', task_path(task.id), class: 'btn-xs btn-danger', method: :delete
    - else
      td.col-md-3
        .btn-group
          = button_to 'Edit task', edit_user_task_path(current_user.id, task.id), class: 'btn-xs btn-primary', method: :get
          = button_to 'Delete task', user_task_path(current_user.id, task.id), class: 'btn-xs btn-danger', method: :delete

app/views/shared/_tasks_table.html.slim
- if @tasks.empty?
  h2 There are no tasks created yet.
- else
    table.table-bordered.table-hover.table-index
      thead
        tr
          th ID
          th Name
          th Description
          th State
          - if current_user.role == 'admin'
            th User
          - if current_user
            th Actions
      tbody
        - @tasks.each do |task|
          = render 'shared/task', task: task